### ISSUE TITLE
payload validation error for Default App client update

### ISSUE THREAD

**Issue by ukayani** [ukayani/auth0-deploy#5]
Using the following `config.json`

```
{
	"allowed_clients": null,
	"allowed_logout_urls": null,
	"allowed_origins": null,
	"callback_url_template": false,
	"callbacks": null,
	"client_id": "xbdof-iI9cCpXmt_0pP6PbBa6zzhQSI1",
	"config_route": null,
	"custom_login_page_on": false,
	"global": false,
	"grant_types": [
		"implicit",
		"authorization_code",
		"client_credentials",
		"refresh_token"
	],
	"is_first_party": true,
	"jwt_configuration": {
		"lifetime_in_seconds": "36000",
		"secret_encoded": false
	},
	"name": "Default App",
	"tenant": "bamboo"
}```

When trying to do a deploy for the Default App, we are getting validation errors:

```bash
xf186001@MUSXF186001-209:~/workplace/bamboo-config/components » auth0-deploy client Default\ App -c {client_id} -s {client_secret} -d bamboo.auth0.com                        1 ↵
Updating client: Default App
Payload validation error: 'Additional properties not allowed: tenant,global,config_route,client_id,callback_url_template'.
xf186001@MUSXF186001-209:~/workplace/bamboo-config/components » auth0-deploy client Default\ App -c {client_id} -s {client_secret} -d bamboo.auth0.com                        1 ↵
Updating client: Default App
Payload validation error: 'Expected type array but found type null' on property callbacks (A set of URLs that are valid to call back from Auth0 when authenticating users). (also) Payload validation error: 'Expected type array but found type null' on property allowed_origins (A set of URLs that represents valid origins for CORS). (also) Payload validation error: 'Expected type array but found type null' on property allowed_logout_urls (A set of URLs that are valid to redirect to after logout from Auth0). (also) Payload validation error: 'Expected type array but found type null' on property allowed_clients (Ids of clients that will be allowed to perform delegation requests. Clients that will be allowed to make delegation request. By default, all your clients will be allowed. This field allows you to specify specific clients). (also) Payload validation error: 'Additional properties not allowed: secret_encoded' on property jwt_configuration (An object that holds settings related to how JWTs are created).
```

From @xiananfan

> I first removed the "tenant,global,config_route,client_id,callback_url_template" fields from the config.json. Then I encounter the validation error above.
> 
> So it seems the tool is complaining the missing fields "callbacks", "allowed_origins", "allowed_logout_urls", "allowed_clients". Add additional field inside the "jwt_configuration" object.
> 
> I could provide the above fields in a real client. However, if you notice, I was trying to update the "Default App" client, which was there by default when you create a new tenant in auth0. I was wondering if you could consider allowing the value to not be there as well. Because the value is a direct dump from the management api v2. In other words, missing the value should be valid, and not encounter a validation error.
>

**Comment by ukayani** [comment]
@xiananfan have you tried omitting those fields instead of including them and making them `null` ? Only include fields which you wish to create/update

**Comment by xiananfan** [comment]
@ukayani , if you take a close look at the config.json, "callbacks", "allowed_origins", "allowed_logout_urls", "allowed_clients" are not there. I think the tools want them to be there, but also don't want them to be null as well.

I think the tool should allow them to not be there.

(Thanks for creating the issue for me).

**Comment by ukayani** [comment]
@xiananfan , the validation error is actually coming from auth0 management
API. I have some default fields that i include but i dont think i include
callbacks/ allowed_origins as defaults. Ill take a look at the code. Could
you supply your new ‘config.json’ that removes the fields you said you
removed such as ‘global’?

**Comment by xiananfan** [comment]
hi @ukayani ,

The direct dump using management api v2 gives the following for Default App:
```
{
    "tenant": "bamboo",
    "name": "Default App",
    "callbacks": null,
    "global": false,
    "allowed_clients": null,
    "allowed_logout_urls": null,
    "is_first_party": true,
    "is_token_endpoint_ip_header_trusted": false,
    "signing_keys": [
      {
        "cert": "REMOVED",
        "pkcs7": "REMOVED",
        "subject": "/CN=bamboo.auth0.com"
      }
    ],
    "allowed_origins": null,
    "client_id": "xbdof-iI9cCpXmt_0pP6PbBa6zzhQSI1",
    "callback_url_template": false,
    "config_route": null,
    "client_secret": "REMOVED",
    "jwt_configuration": {
      "alg": "RS256",
      "lifetime_in_seconds": 36000,
      "secret_encoded": false
    },
    "token_endpoint_auth_method": "none",
    "app_type": "regular_web",
    "grant_types": [
      "implicit",
      "authorization_code",
      "refresh_token"
    ],
    "custom_login_page_on": false
}
```
(I changed 3 sensitive fields' value to REMOVED)

I was able to complete an update of this client until I reduced the config to the following:
```
{
	"custom_login_page_on": false,
	"grant_types": [
		"implicit",
		"authorization_code",
		"refresh_token"
	],
	"is_first_party": true,
	"jwt_configuration": {
		"lifetime_in_seconds": 36000
	},
	"name": "Default App"
}
```

Thanks.

**Comment by ukayani** [comment]
It is strange that they return `null` for some of the fields since they don't accept null as a valid value for create/update. 
The problem is that you can't take the dump from the management API and use that to create a client; some of the fields are not allowed for create/update operations.  Each of the create operations in their management API list the fields which are required/allowed.

One change I could make is to ignore fields which are set to `null` but I personally don't see a point of including a field with `null` as the value.

**Comment by ukayani** [comment]
You should base your client  `config.json` from the Body Sample provided here
https://auth0.com/docs/api/management/v2#!/Clients/post_clients

**Comment by xiananfan** [comment]
Hi @ukayani , thank you for looking into the issue. Free free to resolve the issue!

**Comment by ukayani** [comment]
@xiananfan no problem. Cheers
