### ISSUE TITLE
Auth0-deploy-cli v2 released. Link to that repo?

### ISSUE THREAD

**Issue by stevezau** [ukayani/auth0-deploy#9]
Hi @ukayani,

We spoke a long while back about merging auth0-deploy with auth0-deploy-cli.

We have finally rewritten auth0-deploy-cli to support most objects within Auth0.

I believe this project is no longer maintained. May I suggest a link to auth0-deploy-cli in your readme.md?

**Comment by stevezau** [comment]
v3 now. Anyone? :D

**Comment by ukayani** [comment]
Could you provide me the markdown to the repo you wish to link to?

**Comment by stevezau** [comment]
Well, the offical auth0-deploy-cli was rewritten to support all objects and many other features. You can see it here https://github.com/auth0/auth0-deploy-cli/

Both these tools do similar things.

I'm suggesting to redirect users to that tool if this one is not heavily maintained. Up too you.

**Comment by ukayani** [comment]
I've added a note to the readme @stevezau . Cheers.

**Comment by stevezau** [comment]
👍
